server:
  port: 9090

spring:
  application:
    name: one-light-cache-demo
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

# 配置light-cache 见测试配置 test/resources/application.yml
